export interface Country {
  code: string;
  name: string;
  language: string;
}

export const countries: Country[] = [
  { code: 'US', name: 'United States', language: 'en' },
  { code: 'GB', name: 'United Kingdom', language: 'en' },
  { code: 'KR', name: 'South Korea', language: 'ko' },
  { code: 'JP', name: 'Japan', language: 'ja' },
  { code: 'FR', name: 'France', language: 'fr' },
  { code: 'DE', name: 'Germany', language: 'de' },
  { code: 'IN', name: 'India', language: 'hi' },
  { code: 'ES', name: 'Spain', language: 'es' },
  { code: 'IT', name: 'Italy', language: 'it' },
  { code: 'CN', name: 'China', language: 'zh' },
  { code: 'RU', name: 'Russia', language: 'ru' },
  { code: 'BR', name: 'Brazil', language: 'pt' },
  { code: 'TR', name: 'Turkey', language: 'tr' },
  { code: 'SE', name: 'Sweden', language: 'sv' },
  { code: 'DK', name: 'Denmark', language: 'da' },
  { code: 'NO', name: 'Norway', language: 'no' },
  { code: 'NL', name: 'Netherlands', language: 'nl' },
  { code: 'MX', name: 'Mexico', language: 'es' },
  { code: 'AR', name: 'Argentina', language: 'es' },
  { code: 'AU', name: 'Australia', language: 'en' },
  { code: 'CA', name: 'Canada', language: 'en' },
  { code: 'TH', name: 'Thailand', language: 'th' },
  { code: 'TW', name: 'Taiwan', language: 'zh' },
  { code: 'HK', name: 'Hong Kong', language: 'zh' },
  { code: 'PH', name: 'Philippines', language: 'tl' },
  { code: 'ID', name: 'Indonesia', language: 'id' },
  { code: 'MY', name: 'Malaysia', language: 'ms' },
  { code: 'SG', name: 'Singapore', language: 'en' },
  { code: 'NZ', name: 'New Zealand', language: 'en' },
  { code: 'ZA', name: 'South Africa', language: 'en' },
  { code: 'PL', name: 'Poland', language: 'pl' },
  { code: 'UA', name: 'Ukraine', language: 'uk' },
  { code: 'CZ', name: 'Czech Republic', language: 'cs' },
  { code: 'HU', name: 'Hungary', language: 'hu' },
  { code: 'RO', name: 'Romania', language: 'ro' },
  { code: 'GR', name: 'Greece', language: 'el' },
  { code: 'PT', name: 'Portugal', language: 'pt' },
  { code: 'FI', name: 'Finland', language: 'fi' },
  { code: 'IE', name: 'Ireland', language: 'en' },
  { code: 'IL', name: 'Israel', language: 'he' },
  { code: 'EG', name: 'Egypt', language: 'ar' },
  { code: 'NG', name: 'Nigeria', language: 'en' },
  { code: 'CO', name: 'Colombia', language: 'es' },
  { code: 'CL', name: 'Chile', language: 'es' },
  { code: 'PK', name: 'Pakistan', language: 'ur' },
  { code: 'BD', name: 'Bangladesh', language: 'bn' },
  { code: 'VN', name: 'Vietnam', language: 'vi' },
];
